# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3195294712ce32c60dbba87cffc73458b9fd0c3a4a4d609a99e5721bf56011a3325988b91f41a02aebc34c6887d76c073468f2d5f602a7e05e9fd1e9384cb5a1

test:
  secret_key_base: 6f1a2bfd888614c4b42951c7c452840ed04d365242cde879bcb320ac6c9337880c4bd376188b7f6446a6f8c9a6817fb81c76c57189c2d9b94a1568933d209db8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
